name: "Quote Duplicates Linter"

on:
  pull_request_target:
    types: [opened, reopened, synchronize]
    paths:
      - 'quotes.json'

permissions:
  issues: write

jobs:
  comment-duplicates:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout PR code
        uses: actions/checkout@v3
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Check for duplicate quotes
        id: dupes
        run: |
          set +e
          OUTPUT=$(node scripts/check-duplicates.js 2>&1)
          echo "$OUTPUT"
          echo "::set-output name=result::$OUTPUT"

      - name: Comment on PR with duplicates
        if: contains( steps.dupes.outputs.result, '::duplicate-quotes-found::' )
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const raw = `${{ steps.dupes.outputs.result }}`;
            const dupList = raw.split('::duplicate-quotes-found::')[1].trim();
            const body = `
⚠️ Duplicate quotes detected in \`quotes.json\`:

\`\`\`
${dupList}
\`\`\`

Please remove or reword them before merging.
`;
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.pull_request.number,
              body
            });

      - name: Fail on duplicates
        if: contains( steps.dupes.outputs.result, '::duplicate-quotes-found::' )
        run: |
          echo "::error::Duplicate quotes found—see comment above."
          exit 1
